<?php
/*
 *  This file is part of StuckMVC <https://stuck1a.de/coding/stuckmvc>,
 *  Copyright (c) 2021.
 *  The StuckMVC framework is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License version 3 as published by
 *  the Free Software Foundation.
 *  
 *  It is distributed in the hope that it will be useful, but without any warranty;
 *  without even the implied warranty of merchantability of fitness for a
 *  particular purpose. See the GNU General Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along with
 *  StuckMVC. If not, see <https://www.gnu.org/licenses/>. 
 *
 *  FOR A SOMEWHAT FREER WORLD.
 */

namespace Stuck1A\StuckMVC\Core\Autoloader;


return [
  'Smarty' => 'vendor/smarty/smarty/libs/Smarty.class.php',
  'SmartyBC' => 'vendor/smarty/smarty/libs/SmartyBC.class.php',
  'SmartyCompilerException' => 'vendor/smarty/smarty/libs/sysplugins/smartycompilerexception.php',
  'SmartyException' => 'vendor/smarty/smarty/libs/sysplugins/smartyexception.php',
  'Smarty_Autoloader' => 'vendor/smarty/smarty/libs/Autoloader.php',
  'Smarty_CacheResource' => 'vendor/smarty/smarty/libs/sysplugins/smarty_cacheresource.php',
  'Smarty_CacheResource_Custom' => 'vendor/smarty/smarty/libs/sysplugins/smarty_cacheresource_custom.php',
  'Smarty_CacheResource_KeyValueStore' => 'vendor/smarty/smarty/libs/sysplugins/smarty_cacheresource_keyvaluestore.php',
  'Smarty_Data' => 'vendor/smarty/smarty/libs/sysplugins/smarty_data.php',
  'Smarty_Internal_Block' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_block.php',
  'Smarty_Internal_CacheResource_File' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_cacheresource_file.php',
  'Smarty_Internal_CompileBase' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compilebase.php',
  'Smarty_Internal_Compile_Append' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_append.php',
  'Smarty_Internal_Compile_Assign' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_assign.php',
  'Smarty_Internal_Compile_Block' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_block.php',
  'Smarty_Internal_Compile_Block_Child' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_block_child.php',
  'Smarty_Internal_Compile_Block_Parent' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_block_parent.php',
  'Smarty_Internal_Compile_Blockclose' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_block.php',
  'Smarty_Internal_Compile_Break' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_break.php',
  'Smarty_Internal_Compile_Call' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_call.php',
  'Smarty_Internal_Compile_Capture' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_capture.php',
  'Smarty_Internal_Compile_CaptureClose' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_capture.php',
  'Smarty_Internal_Compile_Child' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_child.php',
  'Smarty_Internal_Compile_Config_Load' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_config_load.php',
  'Smarty_Internal_Compile_Continue' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_continue.php',
  'Smarty_Internal_Compile_Debug' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_debug.php',
  'Smarty_Internal_Compile_Else' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_if.php',
  'Smarty_Internal_Compile_Elseif' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_if.php',
  'Smarty_Internal_Compile_Eval' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_eval.php',
  'Smarty_Internal_Compile_Extends' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_extends.php',
  'Smarty_Internal_Compile_For' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_for.php',
  'Smarty_Internal_Compile_Forclose' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_for.php',
  'Smarty_Internal_Compile_Foreach' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_foreach.php',
  'Smarty_Internal_Compile_Foreachclose' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_foreach.php',
  'Smarty_Internal_Compile_Foreachelse' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_foreach.php',
  'Smarty_Internal_Compile_Forelse' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_for.php',
  'Smarty_Internal_Compile_Function' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_function.php',
  'Smarty_Internal_Compile_Functionclose' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_function.php',
  'Smarty_Internal_Compile_If' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_if.php',
  'Smarty_Internal_Compile_Ifclose' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_if.php',
  'Smarty_Internal_Compile_Include' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_include.php',
  'Smarty_Internal_Compile_Include_Php' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_include_php.php',
  'Smarty_Internal_Compile_Insert' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_insert.php',
  'Smarty_Internal_Compile_Ldelim' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_ldelim.php',
  'Smarty_Internal_Compile_Make_Nocache' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_make_nocache.php',
  'Smarty_Internal_Compile_Nocache' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_nocache.php',
  'Smarty_Internal_Compile_Nocacheclose' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_nocache.php',
  'Smarty_Internal_Compile_Parent' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_parent.php',
  'Smarty_Internal_Compile_Private_Block_Plugin' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_private_block_plugin.php',
  'Smarty_Internal_Compile_Private_ForeachSection' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_private_foreachsection.php',
  'Smarty_Internal_Compile_Private_Function_Plugin' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_private_function_plugin.php',
  'Smarty_Internal_Compile_Private_Modifier' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_private_modifier.php',
  'Smarty_Internal_Compile_Private_Object_Block_Function' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_private_object_block_function.php',
  'Smarty_Internal_Compile_Private_Object_Function' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_private_object_function.php',
  'Smarty_Internal_Compile_Private_Php' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_private_php.php',
  'Smarty_Internal_Compile_Private_Print_Expression' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_private_print_expression.php',
  'Smarty_Internal_Compile_Private_Registered_Block' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_private_registered_block.php',
  'Smarty_Internal_Compile_Private_Registered_Function' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_private_registered_function.php',
  'Smarty_Internal_Compile_Private_Special_Variable' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_private_special_variable.php',
  'Smarty_Internal_Compile_Rdelim' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_rdelim.php',
  'Smarty_Internal_Compile_Section' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_section.php',
  'Smarty_Internal_Compile_Sectionclose' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_section.php',
  'Smarty_Internal_Compile_Sectionelse' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_section.php',
  'Smarty_Internal_Compile_Setfilter' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_setfilter.php',
  'Smarty_Internal_Compile_Setfilterclose' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_setfilter.php',
  'Smarty_Internal_Compile_Shared_Inheritance' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_shared_inheritance.php',
  'Smarty_Internal_Compile_While' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_while.php',
  'Smarty_Internal_Compile_Whileclose' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_while.php',
  'Smarty_Internal_Config_File_Compiler' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_config_file_compiler.php',
  'Smarty_Internal_Configfilelexer' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_configfilelexer.php',
  'Smarty_Internal_Configfileparser' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_configfileparser.php',
  'Smarty_Internal_Data' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_data.php',
  'Smarty_Internal_Debug' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_debug.php',
  'Smarty_Internal_ErrorHandler' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_errorhandler.php',
  'Smarty_Internal_Extension_Handler' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_extension_handler.php',
  'Smarty_Internal_Method_AddAutoloadFilters' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_addautoloadfilters.php',
  'Smarty_Internal_Method_AddDefaultModifiers' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_adddefaultmodifiers.php',
  'Smarty_Internal_Method_Append' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_append.php',
  'Smarty_Internal_Method_AppendByRef' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_appendbyref.php',
  'Smarty_Internal_Method_AssignByRef' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_assignbyref.php',
  'Smarty_Internal_Method_AssignGlobal' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_assignglobal.php',
  'Smarty_Internal_Method_ClearAllAssign' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_clearallassign.php',
  'Smarty_Internal_Method_ClearAllCache' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_clearallcache.php',
  'Smarty_Internal_Method_ClearAssign' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_clearassign.php',
  'Smarty_Internal_Method_ClearCache' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_clearcache.php',
  'Smarty_Internal_Method_ClearCompiledTemplate' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_clearcompiledtemplate.php',
  'Smarty_Internal_Method_ClearConfig' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_clearconfig.php',
  'Smarty_Internal_Method_CompileAllConfig' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_compileallconfig.php',
  'Smarty_Internal_Method_CompileAllTemplates' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_compilealltemplates.php',
  'Smarty_Internal_Method_ConfigLoad' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_configload.php',
  'Smarty_Internal_Method_CreateData' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_createdata.php',
  'Smarty_Internal_Method_GetAutoloadFilters' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_getautoloadfilters.php',
  'Smarty_Internal_Method_GetConfigVariable' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_getconfigvariable.php',
  'Smarty_Internal_Method_GetConfigVars' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_getconfigvars.php',
  'Smarty_Internal_Method_GetDebugTemplate' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_getdebugtemplate.php',
  'Smarty_Internal_Method_GetDefaultModifiers' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_getdefaultmodifiers.php',
  'Smarty_Internal_Method_GetGlobal' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_getglobal.php',
  'Smarty_Internal_Method_GetRegisteredObject' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_getregisteredobject.php',
  'Smarty_Internal_Method_GetStreamVariable' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_getstreamvariable.php',
  'Smarty_Internal_Method_GetTags' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_gettags.php',
  'Smarty_Internal_Method_GetTemplateVars' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_gettemplatevars.php',
  'Smarty_Internal_Method_Literals' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_literals.php',
  'Smarty_Internal_Method_LoadFilter' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_loadfilter.php',
  'Smarty_Internal_Method_LoadPlugin' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_loadplugin.php',
  'Smarty_Internal_Method_MustCompile' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_mustcompile.php',
  'Smarty_Internal_Method_RegisterCacheResource' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_registercacheresource.php',
  'Smarty_Internal_Method_RegisterClass' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_registerclass.php',
  'Smarty_Internal_Method_RegisterDefaultConfigHandler' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_registerdefaultconfighandler.php',
  'Smarty_Internal_Method_RegisterDefaultPluginHandler' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_registerdefaultpluginhandler.php',
  'Smarty_Internal_Method_RegisterDefaultTemplateHandler' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_registerdefaulttemplatehandler.php',
  'Smarty_Internal_Method_RegisterFilter' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_registerfilter.php',
  'Smarty_Internal_Method_RegisterObject' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_registerobject.php',
  'Smarty_Internal_Method_RegisterPlugin' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_registerplugin.php',
  'Smarty_Internal_Method_RegisterResource' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_registerresource.php',
  'Smarty_Internal_Method_SetAutoloadFilters' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_setautoloadfilters.php',
  'Smarty_Internal_Method_SetDebugTemplate' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_setdebugtemplate.php',
  'Smarty_Internal_Method_SetDefaultModifiers' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_setdefaultmodifiers.php',
  'Smarty_Internal_Method_UnloadFilter' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_unloadfilter.php',
  'Smarty_Internal_Method_UnregisterCacheResource' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_unregistercacheresource.php',
  'Smarty_Internal_Method_UnregisterFilter' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_unregisterfilter.php',
  'Smarty_Internal_Method_UnregisterObject' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_unregisterobject.php',
  'Smarty_Internal_Method_UnregisterPlugin' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_unregisterplugin.php',
  'Smarty_Internal_Method_UnregisterResource' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_unregisterresource.php',
  'Smarty_Internal_Nocache_Insert' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_nocache_insert.php',
  'Smarty_Internal_ParseTree' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_parsetree.php',
  'Smarty_Internal_ParseTree_Code' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_parsetree_code.php',
  'Smarty_Internal_ParseTree_Dq' => 'vendor/smarty/smarty/libs/sysplugins/smarty_internal_parsetree_dq.php',
];
